service: urizip
api_version: 1
threadsafe: false
runtime: python27

default_expiration: 0m

handlers:

- url: /
  static_files: static/index.html
  upload: static\/index\.html

- url: /
  static_dir: static


